version: '3'

services:
  ss-libev:
    build: .
    container_name: ss-libev
    restart: always
    ports:
      - '8388:8388/udp'
      - '8388:8388/tcp'
    environment:
      - PASSWORD=Password
      - TIMEOUT=300
      - METHOD=aes-256-gcm
      - DNS_ADDRS=114.114.114.114,8.8.8.8
