version: '3'

services:
  ss-libev:
    build: ./libev
    container_name: ss-libev
    restart: always
    # ports: # 映射端口，如果需要让其他机器访问，请取消注释
    #   - '8388:8388/udp'
    #   - '8388:8388/tcp'
    environment:
      - PASSWORD=Password
      - TIMEOUT=300
      - METHOD=aes-256-gcm
      - DNS_ADDRS=114.114.114.114,8.8.8.8
  ss-manager:
    build: ./manager
    container_name: ss-manager
    restart: always
    volumes:
      - ./.ssconfig.json:/.ssconfig.json:ro
    ports:
      - "1080:1080/udp"   # ss-local 代理端口
      - "1080:1080/tcp"   # ss-local 代理端口
      - "5000:5000"   # 管理界面端口
